[settings]
experimental = true

[tools]
# language support
go = "latest"
node = 'latest'
rust = { version = 'latest', profile="minimal", components = 'rustc,cargo,rustfmt,rust-std,rust-analyzer,clippy,llvm-tools' }

# tools
fzf = 'latest'
fd = 'latest'
lua = 'latest'
zoxide = 'latest'
ripgrep = "latest"
uv = "latest"
bat = "latest"
jq = "latest"
usage = "latest"
eza = "latest"
"ubi:JanDeDobbeleer/oh-my-posh" = "latest"

# tuis
"asdf:neovim" = "ref:nightly"
lazygit = 'latest'
yazi = "latest"

# formatters
"cargo:stylua" = "latest"
"pipx:gersemi" = "latest"
"pipx:black" = "latest"
"pipx:beautysh" = "latest"
"pipx:mdformat" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"npm:@fsouza/prettierd" = "latest"

# language servers
"npm:vscode-json-languageservice" = "latest"
"npm:bash-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:cmake-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"asdf:lua-language-server" = "latest"
clang-format = "20.1.8"
cmake = "3.31.6"
"pipx:clangd" = "latest"
"pipx:pylatexenc" = "latest"
"pipx:compdb" = "latest"
"ubi:mikew/nvrh" = "latest"
"cargo:bob-nvim" = "latest"
"pipx:neovim-remote" = "latest"
trivy = "latest"
"cargo:tealdeer" = "latest"
"npm:tree-sitter-cli" = "0.25"

[env]
UV_NATIVE_TLS = "true"
_.file = "~/.env"
